matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.1
      
      before_install:
        - brew update
        - brew upgrade node
        - npm install -g react-native-cli
        
      install:
        - npm install
        
    - language: android
      jdk: oraclejdk8

      android:
        components:
          - build-tools-19.0.1
      
      before_install:
        - nvm install node
        - npm install -g react-native-cli
      
      install:
        - npm install
        - cd android && ./gradlew assembleRelease
        
      script:
          - echo "Travis branch is $TRAVIS_BRANCH"
          - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
