matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.1
      before_install:
          - brew update
          - brew install node
          - npm install -g react-native-cli
