matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.1
      before_install:
        - brew update
        - brew upgrade node
        - npm install -g react-native-cli
    - language: android
      android:
        components:
          - tools
          - platform-tools
          - tools

          # The BuildTools version used by your project
          - build-tools-25.0.0

          # The SDK version used to compile your project
          - android-25
